fix a django migration error when applying profiles.0024_populate_region
django.db.utils.ProgrammingError: column profiles_profile.external_id does not exist