Add registration (#1181)
* Add QR code generator

* Add ability to print event badges

* Hide addon options when only 1 opiton

* Add setting to hide member pricing from non-members

* Add attendance dates to registration

* Add RegistrantChildEvent model

* Refactor payment handling to a util so it is reusable

* Add setting to turn off pre-registration pricing page

* Allow registration to child events

* Update badge to display child events registered

* Add start/end date validation to child events

* Fix bug when adding additional registrants

* Fix typos

* List sub-events on registration edit page

* Remove categories with no sub-categories and sort alphabetically

* Add more registrant info to child event selection

* Allow editing of sub-events

* Update verbiage for registration edit if nested events enabled

* Filter out past child events from registration

* Filter out past events from child event registration

* Redirect child event registration to parent

* Don't allow editing child events if registration closed

* Filter out at capacity child events from registration

* Add validation to prevent selecting repeat sub events

* Fix attendance days in registrant edit

* Fix css on child event registration

* Only update attendance dates if applicable

* Hide days price covers if not using nested events

* Adjust a few things if nested events is turned off

* Fix formatting of attendance dates options

* Fix bug with missing attendance dates on regular form

* fix an AttributeError on "Manage Custom Registration Form"

 'NoneType' object has no attribute 'requires_attendance_dates'

* combine 3 migrations into one