avoid missing the validation from super call on the uniqueness for the field name
IntegrityError: duplicate key value violates unique constraint "memberships_membershiptype_name_key"