Add event cancellation fields (#1159)
* Add cancellation fields to events

* Hide cancel link when past cancellation window

* Add cancellation fee as invoice line item

* Add cancellation link to 2 more pages

* Add warning modal on cancellation

* Add allow refund site setting

* Add refund info to cancellation modal

* Add cancellation confirmation messages

* Update cancellation email to refer to refunds

* Cleanup for cancellation messaging

* Refund updates the invoice

* Add manual refunds

* Execute actual refund through Stripe

* Check merchange acct when getting Stripe payments

* Cleanup

* Move allow_refunds to settings.json

* fix conflicting migrations

* Fix bugs with PercentField

* Fix bug with displaying decimal places when cancelling

* Add refunds to Payment History

* Add missing translation

* Add accounting entries for cancellation fees during refund

* fix a typo

* make accounting entries for refund

... and added a "Sales Returns and Allowances" account (which is a contra revenue account)

* fix AttributeError: 'NoneType' object has no attribute 'email'

* fix AttributeError

* fix broken links

* fix a 404 when user canceling via cancel_registrant

* Add stripe connect account to refunds

* Add error message to refund failure email

* Refactor cancellation logic so that it is centralized

* Add option to cancel registration in Refund menu

* fix an AttributeError:

'NoneType' object has no attribute 'username'

* fix a NameError:

name 'registrant' is not defined

* fix another AttributeError at invoice refund

* fix params for refund on stripe connected accounts

- for standard accounts, "stripe_account" needs to be specified
- for express accounts, "reverse_transfer" needs to be set

* Fix bug in cancelling from Refund menu

* Change how cancellation fees are used, and make them adjustable

* Include refunds in invoice reporting

* Minor fixes for new cancellation_fee usage

* Allow readjusting cancellation fee after cancellation

* Fix bug in code that estimates cancellation fees to be applied

---------

Co-authored-by: Jenny Qian <jqian@tendenci.com>