bugfix on event registration with custom form
On event registration, only the first registrant information is required. But the "empty_permitted" failed to add additional registrants (if their info is not provided) with custom form.

AttributeError: 'int' object has no attribute 'price'