replace cchardet with chardet
... because cchardet doesn't support Python 3.11
Python 3.11: Failed to build cchardet
ERROR: Could not build wheels for cchardet, which is required to install pyproject.toml-based projects